# template from https://doc.rust-lang.org/cargo/guide/continuous-integration.html

stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
  only:
    - main
    - merge_requests

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  only:
    - main
    - merge_requests