# template from https://doc.rust-lang.org/cargo/guide/continuous-integration.html

stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  rules:
    # if its a (merge-)commit on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # if merge request exists for this branch
    - if: $CI_MERGE_REQUEST_IID
      when: manual
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  rules:
    # if its a (merge-)commit on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # if merge request exists for this branch
    - if: $CI_MERGE_REQUEST_IID
      when: manual
  script:
    - cargo build --verbose
    - cargo test --verbose
