[package]
name = "bongo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.52"
duplicate = "0.3.0"
sqlparser = "0.13.0"
serde_json = "1.0.74"
serde = { version = "1.0", features = ["derive"] }
tokio-test = "0.4.2"